import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import { ReactElement } from 'react';
import { NextPageWithLayout } from './_app';

const About: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
};

About.getLayout = function getLayout(page: ReactElement) {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};

export default About;
